name: Build and Deploy

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        version: [ 1.19.2 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sed -i "s/{{MCVERSION}}/${{ matrix.version }}/g" .releaserc.json
      - run: cat .releaserc.json
      - uses: codfish/semantic-release-action@v2
        id: semantic
        with:
          additional_packages: "@codedependant/semantic-release-docker@latest"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@codedependant/semantic-release-docker']
        env:
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
