name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: minecraft-fabric-server

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codfish/semantic-release-action@v2
        id: semantic
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new-release: ${{ steps.semantic.outputs.new-release-published }}
      new-version: ${{ steps.semantic.outputs.release-version }}

  build:
    needs: analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 1.19.2, 1.19.4, 1.20, 1.20.1 ]
    steps:
      - uses: actions/checkout@v3
      - uses: codfish/semantic-release-action@v2
        id: semantic
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push for normal versions
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            MINECRAFT_VERSION=${{ matrix.version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-dev
      - name: Build and push semantic versions
        uses: docker/build-push-action@v3
        if: needs.analyze.outputs.new-release
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ needs.analyze.outputs.new-version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}

  description:
    needs: [ analyze, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          readme-filepath: README.md
          short-description: ${{ github.event.repository.description }}
      - name: Bump version and push tag
        id: tag_version
        if: needs.build.outputs.new-release
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ needs.analyze.outputs.new-version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
