name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: minecraft-fabric-server

jobs:
  build:
    strategy:
      matrix:
        version: [ 1.16.5, 1.17.1, 1.18.2, 1.19.2 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codfish/semantic-release-action@v2
        id: semantic
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push for normal versions
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-dev
      - name: Build and push semantic versions
        uses: docker/build-push-action@v3
        if: steps.semantic.outputs.new-release-published
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ steps.semantic.outputs.release-version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}
      - name: Bump version and push tag
        id: tag_version
        if: steps.semantic.outputs.new-release-published
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.semantic.outputs.release-version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          readme-filepath: README.md
          short-description: ${{ github.event.repository.description }}
