name: Process Snapthos

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

env:
  IMAGE_NAME: minecraft-fabric-server

jobs:
  getsnapshot:
    runs-on: ubuntu-latest
    steps:
      - name: set current version
        id: current_version
        run: |
          echo $(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.latest.snapshot') > /tmp/snapshot_version.txt && \
          echo "SNAPSHOT_VERSION=$(cat /tmp/snapshot_version.txt)" >> "$GITHUB_OUTPUT"
      - name: get cache
        id: cache
        uses: actions/cache@v3
        with:
          path: /tmp/snapshot_version.txt
          key: snapshot_version-${{ steps.current_version.outputs.snapshot_version }}
      - name: set output
        id: output
        run: | 
          echo "BUILD=${{ steps.cache.outputs.cache-hit }}" >> "$GITHUB_OUTPUT" && \
          echo "SNAPSHOT_VERSION=$(cat /tmp/snapshot_version.txt)" >> "$GITHUB_STEP_SUMMARY" && \
          echo "CACHED=${{ steps.cache.outputs.cache-hit }}" >> "$GITHUB_STEP_SUMMARY" && \
          echo "SNAPSHOT_VERSION=$(cat /tmp/snapshot_version.txt)" >> "$GITHUB_ENV" && \

  build:
    needs: getsnapshot
    if: needs.getsnapshot.outputs.CACHED != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codfish/semantic-release-action@v2
        id: semantic
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push for normal versions
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          no-cache: true
          build-args: |
            MINECRAFT_VERSION=${{ needs.getsnapshot.outputs.snapshot_version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.getsnapshot.outputs.snapshot_version }}-dev
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:snapshot-latest
      - name: Build and push semantic versions
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            MINECRAFT_VERSION=${{ needs.getsnapshot.outputs.snapshot_version }}
          push: true
          no-cache: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.getsnapshot.outputs.snapshot_version }}-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.getsnapshot.outputs.snapshot_version }}
