name: Process Snapshots

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

env:
  IMAGE_NAME: minecraft-fabric-server

jobs:
  getsnapshot:
    runs-on: ubuntu-latest
    steps:
      - name: set current version
        id: current_version
        run: |
          echo "$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.latest.snapshot')" > /tmp/snapshot_version.txt
          echo "SNAPSHOT_VERSION=$(cat /tmp/snapshot_version.txt)" >> "$GITHUB_OUTPUT"
      - name: get cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/snapshot_version.txt
          key: snapshot_version-${{ steps.current_version.outputs.SNAPSHOT_VERSION }}
      - name: set output
        id: output
        run: |
          echo "SNAPSHOT_VERSION=$(cat /tmp/snapshot_version.txt)" >> "$GITHUB_STEP_SUMMARY"
          echo "Cache key: snapshot_version-${{ steps.current_version.outputs.SNAPSHOT_VERSION }}" >> "$GITHUB_STEP_SUMMARY"
          echo "CACHED=${{ steps.cache.outputs.cache-hit }}" >> "$GITHUB_STEP_SUMMARY"
          echo "SNAPSHOT_VERSION=$(cat /tmp/snapshot_version.txt)" >> "$GITHUB_ENV"
    outputs:
      CACHED: ${{ steps.cache.outputs.cache-hit }}
      SNAPSHOT_VERSION: ${{ env.SNAPSHOT_VERSION }}

  build:
    needs: getsnapshot
    if: needs.getsnapshot.outputs.CACHED != 'true'
    runs-on: ubuntu-latest
    env:
      SNAPSHOT_VERSION: ${{ needs.getsnapshot.outputs.SNAPSHOT_VERSION }}
    steps:
      - name: set output
        id: output
        run: |
          echo "SNAPSHOT_VERSION at build=${{ env.SNAPSHOT_VERSION }}" >> "$GITHUB_STEP_SUMMARY"
          echo "CACHED at build=${{ needs.getsnapshot.outputs.CACHED }}" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ env.SNAPSHOT_VERSION }}" > /tmp/snapshot_version.txt
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: log the version
        run: |
          echo "I see the version as: ${{env.SNAPSHOT_VERSION}}" >> "$GITHUB_STEP_SUMMARY"
      - name: Build and push for normal versions
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          no-cache: true
          build-args: |
            MINECRAFT_VERSION=${{ env.SNAPSHOT_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:snapshot-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SNAPSHOT_VERSION }}-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SNAPSHOT_VERSION }}
      - name: set cache
        id: cache-set
        uses: actions/cache/save@v4
        with:
          path: /tmp/snapshot_version.txt
          key: snapshot_version-${{ env.SNAPSHOT_VERSION }}
